name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      fauna:
        image: fauna/faunadb
        ports:
          - 8443:8443
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/gallium'
        cache: 'npm'
    - run: npm ci
    - run: npm run unit
